name: Test SSH to EC2

on:
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.90.238.34 "echo SSH connection success!"
