name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Connect to EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.90.238.34 << 'EOF'
            cd /var/www/project/cargo-service  # replace with your actual path
            git pull origin main
            echo "✅ Code pulled from GitHub"
            # Optionally restart services here:
            # sudo systemctl restart nginx
            # sudo systemctl restart php8.1-fpm
            echo "✅ Deployment completed!"
          EOF
