name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@52.90.238.34 << 'EOF'
          cd /home/ubuntu/var/www/project/cargo-service  # Your app path
          git pull origin main
          # Optionally restart services (nginx, apache, etc.)
          echo "Deployment complete"
        EOF
