name: Test SSH Key Secret

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check if secret is available
        run: |
          if [ -z "${{ secrets.EC2_SSH_KEY }}" ]; then
            echo "❌ EC2_SSH_KEY is EMPTY"
            exit 1
          else
            echo "✅ EC2_SSH_KEY is present!"
          fi

